# Generated by Django 4.2.13 on 2024-07-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_remove_checkbox_description_checkbox_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkbox',
            old_name='user',
            new_name='author',
        ),
    ]
