# Generated by Django 4.2.13 on 2024-07-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_rename_title_checkbox_add_to_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkbox',
            old_name='add_to_list',
            new_name='title',
        ),
    ]
