# Generated by Django 4.2.13 on 2024-06-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
