# Generated by Django 4.2.13 on 2024-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='news',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journal',
            name='news_events',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'High Impact News'), (2, 'Medium Impact News'), (3, 'Low Impact News')], default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='watchlist',
            field=models.CharField(choices=[('eur/usd', 'EUR/USD'), ('gbp/usd', 'GBP/USD'), ('usd/cad', 'USD/CAD'), ('eur/gbp', 'EUR/GBP'), ('treasuries', 'TREASURIES'), ('bond yields', 'BOND YIELDS'), ('s&p500', 'S&P500'), ('nasdaq100', 'NASDAQ100'), ('dxy', 'DXY')], default='dxy', max_length=50),
        ),
    ]
