# Generated by Django 4.2.13 on 2024-06-26 23:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_blog', '0004_journal_news_journal_news_events_journal_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='journal',
            name='chart_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
