# Generated by Django 4.2.13 on 2024-06-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_blog', '0005_alter_comment_options_alter_journal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='news_events',
            field=models.CharField(choices=[('none', 'None'), ('h', 'High Impact News'), ('m', 'Medium Impact News'), ('l', 'Low Impact News')], default='None'),
        ),
    ]
