# Generated by Django 4.2.13 on 2024-06-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_blog', '0006_alter_journal_news_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='news_events',
            field=models.CharField(choices=[('None', 'None'), ('High Impact News', 'H'), ('Medium Impact News', 'M'), ('Low Impact News', 'L')], default='None'),
        ),
    ]
