# Generated by Django 4.2.13 on 2024-07-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_blog', '0008_alter_journal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
